# Generated by Django 3.2 on 2022-10-20 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPageMaster',
            fields=[
                ('contentid', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Datemodified', models.DateField(auto_now_add=True)),
                ('display', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1)),
                ('displayorder', models.IntegerField(default=1)),
                ('upload', models.ImageField(blank=True, help_text='Maximum file size allowed is 2Mb', null=True, upload_to='uploads/', validators=[home.models.validate_image])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GalleryPageMaster',
            },
        ),
    ]
