# Generated by Django 3.2 on 2022-11-11 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20221110_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agemaster',
            name='hide',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='materialmaster',
            name='hide',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=1),
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('productid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(default=1)),
                ('hide', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=1)),
                ('Datemodified', models.DateField(auto_now_add=True)),
                ('productimage', models.ImageField(blank=True, help_text='Maximum file size allowed is 2Mb', null=True, upload_to='product/', validators=[home.models.validate_image])),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materialmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PRODUCTMASTER',
            },
        ),
    ]
