# Generated by Django 3.2 on 2022-11-11 16:22

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221111_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='productimage',
            field=models.ImageField(blank=True, help_text='Maximum file size allowed is 2Mb', null=True, upload_to='media/', validators=[home.models.validate_image]),
        ),
    ]
