# Generated by Django 3.2 on 2022-11-12 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_alter_productmaster_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAgeWiseList',
            fields=[
                ('productid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=1)),
                ('hide', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=1)),
                ('stock', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1)),
                ('Datemodified', models.DateField(auto_now_add=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.agemaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PRODUCTAGEWISELIST',
                'unique_together': {('productid', 'age')},
            },
        ),
    ]
