# Generated by Django 3.2 on 2022-11-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20221112_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
